//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceClone.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eCommerceClone.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string AddItemPageTitle {
            get {
                return ResourceManager.GetString("AddItemPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCommerce App.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string DetailedItemPageItemAddButtonText {
            get {
                return ResourceManager.GetString("DetailedItemPageItemAddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        internal static string DetailedItemPageItemCategoryFieldTitle {
            get {
                return ResourceManager.GetString("DetailedItemPageItemCategoryFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        internal static string DetailedItemPageItemDescription {
            get {
                return ResourceManager.GetString("DetailedItemPageItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string DetailedItemPageItemNameField {
            get {
                return ResourceManager.GetString("DetailedItemPageItemNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string LicenseAgreement {
            get {
                return ResourceManager.GetString("LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listings Page.
        /// </summary>
        internal static string ListingPageTitle {
            get {
                return ResourceManager.GetString("ListingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSourceLicenses.
        /// </summary>
        internal static string OpenSourceLicenses {
            get {
                return ResourceManager.GetString("OpenSourceLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate App.
        /// </summary>
        internal static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
    }
}
